Feature/use npm workspaces
LionWeb-io/lionweb-typescript pull request #113
Opened 2024-01-18 19:48 UTC by joswarmer

I have replaced all shell script by npm commands.  With nmp workspaces it is easy to run an npm command in each package.  This way each package can run their own build/lint/setup/clean/... and it can be run globally.

Also, this is more in line with typical JS/TS projects.
I have used the same setup in lionweb-repository.

2024-01-18 20:04 UTC, joswarmer commented
In addition to this, we can also have `test` scripts per package, that makes is trivial to test each package in isolation (what I have been doing for the last month).

2024-01-19 13:00 UTC, dslmeinte requested changes
Three questions/remarks:

* The per-package `README.md` still mention `build.sh`.
* Is there a replacement for the “quick build” functionality? Maybe not necessary though, as this approach seems to run generally a lot quicker than the script-based one!
* Let's put `"typescript": "5.3.3"` as a dev-dependency in the top-level `package.json`?

2024-01-19 13:06 UTC, joswarmer commented on package.json
> +    "./packages/core",
Yes, it does. That's why I replaced the * with the actual package names.

2024-01-19 13:11 UTC, joswarmer commented on packages/validation/package.json
>      "republish-local": "yarn unpublish-local && yarn publish-local"
Since it is empty, yes I will remove it.

2024-01-19 13:19 UTC, joswarmer commented
- The per-package README.md still mention build.sh.
  Didnt realize this, will change them.
- Is there a replacement for the “quick build” functionality? Maybe not necessary though, as this approach seems to run generally a lot quicker than the script-based one!
  IS identical to `npm run build` in the root folder
- Let's put "typescript": "5.3.3" as a dev-dependency in the top-level package.json?
   Right, makes it more consistent.

2024-01-19 13:44 UTC, merged